language: php
php:
  - '7.2'
  - '7.3'

before_script:
  - composer self-update
  - composer install
  - sudo sysctl -w net.core.rmem_max=26214400
  - sudo sysctl -w net.core.rmem_default=26214400

script:
  - ./vendor/bin/phpunit --configuration ./test/phpunit.xml
