language: php
php:
  #- '8.0'
  - nightly

before_script:
  - composer self-update
  - composer install
  - sudo sysctl -w net.core.rmem_max=26214400
  - sudo sysctl -w net.core.rmem_default=26214400

script:
  - ./vendor/bin/phpunit --configuration ./test/phpunit.xml
